<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadConfirmedBy</key>
	<string>khoindvn.eu.org</string>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>DNSSettings</key>
			<dict>
				<key>DNSProtocol</key>
				<string>HTTPS</string>
				<key>ServerURL</key>
				<string>https://vevrl9air2.cloudflare-gateway.com/dns-query</string>
			</dict>
			<key>OnDemandRules</key>
			<array>
				<dict>
					<key>Action</key>
					<string>Connect</string>
				</dict>
			</array>
			<key>PayloadDisplayName</key>
			<string>Anti-revoke + Adblock</string>
			<key>PayloadIdentifier</key>
			<string>vevrl9air2.cloudflare-gateway.com.profile</string>
			<key>PayloadType</key>
			<string>com.apple.dnsSettings.managed</string>
			<key>PayloadUUID</key>
			<string>vevrl9air2.cloudflare-gateway.com</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>DNSSettings</key>
			<dict>
				<key>DNSProtocol</key>
				<string>HTTPS</string>
				<key>ServerURL</key>
				<string>https://vevrl9air2.cloudflare-gateway.com/dns-query</string>
				<key>SupplementalMatchDomains</key>
				<array>
					<string>ocsp.apple.com</string>
					<string>ocsp2.apple.com</string>
					<string>mesu.apple.com</string>
					<string>valid.apple.com</string>
					<string>crl.apple.com</string>
					<string>certs.apple.com</string>
					<string>appattest.apple.com</string>
					<string>vpp.itunes.apple.com</string>
					<string>guzzoni-apple-com.v.aaplimg.com</string>
					<string>gdmf.apple.com</string>
					<string>axm-app.apple.com</string>
					<string>comm-cohort.ess.apple.com</string>
					<string>comm-main.ess.apple.com</string>
				</array>
			</dict>
			<key>OnDemandRules</key>
			<array>
				<dict>
					<key>Action</key>
					<string>Connect</string>
				</dict>
			</array>
			<key>PayloadDisplayName</key>
			<string>Anti-revoke + Anti-Blacklist</string>
			<key>PayloadIdentifier</key>
			<string>khoindvn.bio.link.profile</string>
			<key>PayloadType</key>
			<string>com.apple.dnsSettings.managed</string>
			<key>PayloadUUID</key>
			<string>dev.khoindvn.bio.link</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>PayloadCertificateFileName</key>
			<string>MITM-CA.crt</string>
			<key>PayloadContent</key>
			<data>
			MIIG1TCCBL2gAwIBAgIQbFWr29AHksedBwzYEZ7WvzANBgkqhkiG
			9w0BAQwFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBK
			ZXJzZXkxFDASBgNVBAcTC0plcnNleSBDaXR5MR4wHAYDVQQKExVU
			aGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNVBAMTJVVTRVJUcnVz
			dCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMjAwMTMw
			MDAwMDAwWhcNMzAwMTI5MjM1OTU5WjBLMQswCQYDVQQGEwJBVDEQ
			MA4GA1UEChMHWmVyb1NTTDEqMCgGA1UEAxMhWmVyb1NTTCBSU0Eg
			RG9tYWluIFNlY3VyZSBTaXRlIENBMIICIjANBgkqhkiG9w0BAQEF
			AAOCAg8AMIICCgKCAgEAhmlzfqO1Mdgj4W3dpBPTVBX1AuvcAyG1
			fl0dUnw/MeueCWzRWTheZ35LVo91kLI3DDVaZKW+TBAsJBjEbYmM
			wcWSTWYCg5334SF0+ctDAsFxsX+rTDh9kSrG/4mp6OShubLaEIUJ
			iZo4t873TuSd0Wj5DWt3DtpAG8T35l/v+xrN8ub8PSSoX5Vkgw+j
			Wf4KQtNvUFLDq8mFWhUnPL6jHAADXpvs4lTNYwOtx9yQtbpxwSt7
			QJY1+ICrmRJB6BuKRt/jfDJF9JscRQVlHIxQdKAJl7oaVnXgDkqt
			k2qddd3kCDXd74gv813G91z7CjsGyJ93oJIlNS3UgFbD6V54JMgZ
			3rSmotYbz98oZxX7MKbtCm1aJ/q+hTv2YK1yMxrnfcieKmOYBbFD
			hnW5O6RMA703dBK92j6XRN2EttLkQuujZgy+jXRKtaWMIlkNkWJm
			OiHmErQngHvtiNkIcjJumq1ddFX4iaTI40a6zgvIBtxFeDs2Rfca
			H73er7ctNUUqgQT5rFgJhMmFx76rQgB5OZUkodb5k2ex7P+Gu4J8
			6bS15094UuYcV09hVeknmTh5Ex9CBKipLS2W2wKBakf+aVYnNCU6
			S0nASqt2xrZpGC1v7v6DhuepyyJtn3qSV2PoBiU5Sql+aARpwUib
			QMGm44gjyNDqDlVp+ShLQlUH9x8CAwEAAaOCAXUwggFxMB8GA1Ud
			IwQYMBaAFFN5v1qqK0rPVIDh2JvAnfKyA2bLMB0GA1UdDgQWBBTI
			2XhootkZaNU9ct5fCj7ctYaGpjAOBgNVHQ8BAf8EBAMCAYYwEgYD
			VR0TAQH/BAgwBgEB/wIBADAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
			KwYBBQUHAwIwIgYDVR0gBBswGTANBgsrBgEEAbIxAQICTjAIBgZn
			gQwBAgEwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDovL2NybC51c2Vy
			dHJ1c3QuY29tL1VTRVJUcnVzdFJTQUNlcnRpZmljYXRpb25BdXRo
			b3JpdHkuY3JsMHYGCCsGAQUFBwEBBGowaDA/BggrBgEFBQcwAoYz
			aHR0cDovL2NydC51c2VydHJ1c3QuY29tL1VTRVJUcnVzdFJTQUFk
			ZFRydXN0Q0EuY3J0MCUGCCsGAQUFBzABhhlodHRwOi8vb2NzcC51
			c2VydHJ1c3QuY29tMA0GCSqGSIb3DQEBDAUAA4ICAQAVDwoIzQDV
			ercT0eYqZjBNJ8VNWwVFlQOtZERqn5iWnEVaLZZdzxlbvz2Fx0Ex
			UNuUEgYkIVM4YocKkCQ7hO5noicoq/DrEYH5IuNcuW1I8JJZ9DLu
			B1fYvIHlZ2JG46iNbVKA3ygAEz86RvDQlt2C494qqPVItRjrz9Yl
			JEGT0DrttyApq0YLFDzf+Z1pkMhh7c+7fXeJqmIhfJpduKc8HEQk
			YQQShen426S3H0JrIAbKcBCiyYFuOhfyvuwVCFDfFvrjADjd4jX1
			uQXd161IyFRbm89s2Oj5oU1wDYz5sx+hoCuh6lSs+/uPuWomIq3y
			1GDFNafW+LsHBU16lQo5Q2yh25laQsKRgyPmMpHJ98edm6y2sHUa
			bASmRHxvGiuwwE25aDU02SAeepyImJ2CzB80YG7WxlynHqNhpE7x
			fC7PzQlLgmfEHdU+tHFeQazRQnrFkW2WkqRGIq7cKRnyypvjPMkj
			eiV9lRdAM9fSJvsB3svUuu1coIG1xxI1yegoGM4r5QP4RGIVvYai
			I76C0djoSbQ/dkIUUXQuB8AL5jyH34g3BZaaXyvpmnV4ilppMXVA
			nAYGON51WhJ6W0xNdNJwzYASZYH+tmCWI+N60Gv2NNMGHwMZ7e9b
			XgzUCZH5FaBFDGR5S9VWqHB73Q+OyIVvIbKYcSc2w/aSuFKGSA==
			</data>
			<key>PayloadDisplayName</key>
			<string>Certificate</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.security.pkcs1.89c6a735-bf8a-47c9-a76a-0501a3fdd16c</string>
			<key>PayloadType</key>
			<string>com.apple.security.pkcs1</string>
			<key>PayloadUUID</key>
			<string>89c6a735-bf8a-47c9-a76a-0501a3fdd16c</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
			<key>Payloadconfirmed</key>
			<string>khoindvn.eu.org</string>
		</dict>
		<dict>
			<key>PayloadCertificateFileName</key>
			<string>MITM-CR.crt</string>
			<key>PayloadContent</key>
			<data>
			MIIGbjCCBFagAwIBAgIRAOFoOc+hfnm8dwEEjufrmSQwDQYJKoZI
			hvcNAQEMBQAwSzELMAkGA1UEBhMCQVQxEDAOBgNVBAoTB1plcm9T
			U0wxKjAoBgNVBAMTIVplcm9TU0wgUlNBIERvbWFpbiBTZWN1cmUg
			U2l0ZSBDQTAeFw0yNDA2MDQwMDAwMDBaFw0yNDA5MDIyMzU5NTla
			MBoxGDAWBgNVBAMTD2tob2luZHZuLmV1Lm9yZzCCASIwDQYJKoZI
			hvcNAQEBBQADggEPADCCAQoCggEBAJSntJ4L+vBtZPxmIX5PhgWd
			5TANlvEFhYoiNkuCtFfb9aHvcSQm7u5+OX2H6NmEiln3THxFnp+n
			zMicXL1XRAu3IjhcNp8Wdlkl5OTV73hNp7ucQi40BLl+cnwp3wjU
			vi6HXUyLL0PtuCjCot77fsD5pEW54E8Uk/XwLhL2P50nB5xodqY7
			EghW9P3ZchxAAGK89WzzzngJqG2y7WfY/dr9Zq0bxmnYhpAf/ofA
			MgH1hQ6c+/tDX+5WJyCWD46ro8iUtc6d8IxozTzdWt/LwjZiRZom
			Hr9xXzFFn2LJVKQJMBg41O6fARmKhXfAun0zluGrkBqqqMPBFzgV
			VrMWilMCAwEAAaOCAnwwggJ4MB8GA1UdIwQYMBaAFMjZeGii2Rlo
			1T1y3l8KPty1hoamMB0GA1UdDgQWBBTgkMkdQ0zEzP1Xbxfv0pCW
			jVeV1TAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNV
			HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwSQYDVR0gBEIwQDA0
			BgsrBgEEAbIxAQICTjAlMCMGCCsGAQUFBwIBFhdodHRwczovL3Nl
			Y3RpZ28uY29tL0NQUzAIBgZngQwBAgEwgYgGCCsGAQUFBwEBBHww
			ejBLBggrBgEFBQcwAoY/aHR0cDovL3plcm9zc2wuY3J0LnNlY3Rp
			Z28uY29tL1plcm9TU0xSU0FEb21haW5TZWN1cmVTaXRlQ0EuY3J0
			MCsGCCsGAQUFBzABhh9odHRwOi8vemVyb3NzbC5vY3NwLnNlY3Rp
			Z28uY29tMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHYAdv+IPwq2
			+5VRwmHM9Ye6NLSkzbsp3GhCCp/mZ0xaOnQAAAGP5ITX/wAABAMA
			RzBFAiEA4tEqZ53D6Km4I0UmllT44zNQvDEnH/ou4RUjcIZbUoAC
			IFoKmhZuT1IM15IbhFTYthPlqoH+44nQTz8NmNhvyUFmAHcAPxdL
			T9ciR1iUHWUchL4NEu2QN38fhWrrwb8ohez4ZG4AAAGP5ITXrwAA
			BAMASDBGAiEA6UbKKcT84BK6JZh0jRosrWtVlk6zFm2qWJS6yzV1
			IRoCIQDxqg2Upe2mwiYnBJjz7jukV9gkrHf3RsfXmbvNqLBDejAa
			BgNVHREEEzARgg9raG9pbmR2bi5ldS5vcmcwDQYJKoZIhvcNAQEM
			BQADggIBAIJ3NiD0RW76UFGJOzMD7sHKMy+Q6I9yWz+BOnmcB7rW
			4H/MAWHXdElceMXV/bYGN7pxyFDRETREuSJ+8qtoKLdiHbfV8feW
			9s5nlqwygmvn2WDzwaKykVfnRcZx96OOKr77vb5TtjAH4uYAj+mZ
			+z3neXOEATO6mRMtMzxvSqFItySUCQhNhAHQBArNGPmNDLL1Or9F
			xcTf9TSkGN9wNWTitkhfhYzkrzNo/T6Kaqew3kMjT3HmJ4amLdub
			J8Cc1ofTJQ2HgHuhH72KfVtvPcLjey6kL53u+bKiRZNxtcxAQDzV
			mtPEmx54D9jl2/63HBnMuRGLI0ymI97E+vEA3Pl3mdRAlpIH4Cys
			27xmXoDUgzB6UDrzfS05smf7PYbFSAasKIjB+pSA8rz5gZOh7TBu
			jnBgwig4ZkBI/S5JtjbaaxUQFWc8V4uVoYsYi9+z2VPSsf967mMA
			8CWYinvDPan3bStkSpZigFIzQWeDV0Ycu9QfccD4g1qYIR2vwx2Y
			zruqrsOxO+tmb05ZjOIo+TOiEA2L02C+RwMloqIQZ91yumdZkzZ3
			lgKjxG3s8n/3j0iykkqcUB3tIWh3XSaEsQ1f9k8h5Cwpn8tQl/s9
			DoVhQ+WuCjt6Ydw5T8wTnOa07u5/6C39h0vF2xeb4WyrpKSGxaCi
			8YCxNUlpAGGVzip4
			</data>
			<key>PayloadDisplayName</key>
			<string>Certificate</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.security.pkcs1.56d2a65a-a9fa-4b2f-80aa-bc7634bdf5df</string>
			<key>PayloadType</key>
			<string>com.apple.security.pkcs1</string>
			<key>PayloadUUID</key>
			<string>56d2a65a-a9fa-4b2f-80aa-bc7634bdf5df</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>PayloadCertificateFileName</key>
			<string>MITM-CL.crt</string>
			<key>PayloadContent</key>
			<data>
			MIIEFTCCAv2gAwIBAgIUTb1Fcak9ZySRjtaQtB8jqE1n9xwwDQYJ
			KoZIhvcNAQELBQAwgagxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpD
			YWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRkwFwYD
			VQQKExBDbG91ZGZsYXJlLCBJbmMuMRswGQYDVQQLExJ3d3cuY2xv
			dWRmbGFyZS5jb20xNDAyBgNVBAMTK01hbmFnZWQgQ0EgMTAxZmRm
			MzgwMGE2ZjU4YzhmMWQ0ZTdhOGVlMjg4NDcwHhcNMjQwNjA1MDQx
			MTAwWhcNMzQwNjAzMDQxMTAwWjAiMQswCQYDVQQGEwJVUzETMBEG
			A1UEAxMKQ2xvdWRmbGFyZTCCASIwDQYJKoZIhvcNAQEBBQADggEP
			ADCCAQoCggEBAJz9xb/NcDUTKBeI3cnrEKKvHAUyoOGX+fDm6O1z
			8+jqa5YzT0ppsrgb1zWzDfbagrlGVxQepS1NwaE4z8KueJgXBK1s
			JAuYFdaaRKpA2KgSKn/X/DIIGT5+x/RfnRFKZ8/8T070NxOkE3Iq
			gjCy4qMi7/Mb5TG6C4pLgfFkeR1+7ptO2GTyKux9MW+Q0Sr6M0Hl
			V7EHCHka4uYIBySk+aYP+6OKbvwFb+9LUW9X5SqAQJAbp6wSNYFm
			Ywnt9Y6AiP6VWhA0dNXrSiUU4odBRfurq2ClSRieteTDIcFWtJG/
			HQ67VuOGlIjlugrZxOrEDPFE0O9dHLvjPld07/k1Hw8CAwEAAaOB
			uzCBuDATBgNVHSUEDDAKBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA
			MB0GA1UdDgQWBBRifOs9Ak3Fj3MdE4GdF0De0jYP0TAfBgNVHSME
			GDAWgBTmbCldNQ3lhMAN8hHLVs+191RUKTBTBgNVHR8ETDBKMEig
			RqBEhkJodHRwOi8vY3JsLmNsb3VkZmxhcmUuY29tLzU4NTUxMDRh
			LTZiNDEtNGJjZC04Y2IwLTJjZDM2NjFiYTJkNi5jcmwwDQYJKoZI
			hvcNAQELBQADggEBAHjtBHv9XXJZ9qK0WTWHjQVmR+HClwH6LXiL
			W2793UfBjtd1ZdqR+WBqli7dfltn0d1BJ5iuop3+5GE3WsXAna+O
			uAWOkJglictsFD26IvUH7wk3zEWLqOEolxvqWSt2LzmRKZdEx4K8
			puzifWO9gnjZSCknkqpP9ennqp1Jn9meiwpzPgTYBi0Y8ANAHS6j
			nq0mfxbqv5t/qtwDVG0qMqW7Pdg89e8L7BZzCRSTpwxhs7OeXNER
			gb5IfAlkNWpzAuRnAzQsQ0gROFqXdv/T/0L8fXO3bTBAsFFi+Uh5
			JUPWAefZPAhq7bm+O+NhDSrlzEOZU/v3RDtSP36O2SUv/eM=
			</data>
			<key>PayloadDisplayName</key>
			<string>Certificate</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.security.pkcs1.ee16ac17-b0c6-4c1c-8193-8d0efa6fe022</string>
			<key>PayloadType</key>
			<string>com.apple.security.pkcs1</string>
			<key>PayloadUUID</key>
			<string>ee16ac17-b0c6-4c1c-8193-8d0efa6fe022</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>PayloadCertificateFileName</key>
			<string>MITM-OC.crt</string>
			<key>PayloadContent</key>
			<data>
			MIIEqjCCA5KgAwIBAgIUDSilBw4UvwemCKvBPwazFes6IF0wDQYJ
			KoZIhvcNAQELBQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBD
			bG91ZEZsYXJlLCBJbmMuMTQwMgYDVQQLEytDbG91ZEZsYXJlIE9y
			aWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRYwFAYDVQQH
			Ew1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlhMB4X
			DTI0MDYwNTA2NDAwMFoXDTM5MDYwMjA2NDAwMFowYjEZMBcGA1UE
			ChMQQ2xvdWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFy
			ZSBPcmlnaW4gQ0ExJjAkBgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2lu
			IENlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
			CgKCAQEAnJBq+5Gxv1vT8wF16Js6suSWfHdgfeQvipyFGy2yiuM+
			xTow3nLfjQ2/hjfjIP5a4qgeVB+j1IJjlh57xfRmPeafkTlG+WzN
			0IDaqtWrIlhxMcN1TqboLoV8XB2VlG1YfaqsOxnAV3L4ydCJP8Es
			GLUx3q2PmByEIKn7hIk/5GP2KKVWr/PU8qHNul1Cow2zCpUy8PD1
			8Hw2NI1pYLfVXYwE2dEDJeVv6augol03KylVHkKqdPD2Lr9SDXW7
			hEDb0xxe1H4fKacA3YOphlusJ/OTcGSnLbftpoOQ5zmTx2+/ylfm
			MGJ5Su/QmXgFrMH1CIUgYoye66OaITJHaPTykwIDAQABo4IBLDCC
			ASgwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMC
			BggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSnpufE
			o+/XVWV/nT5g0b7m0NanoDAfBgNVHSMEGDAWgBQk6FNXXXw0QIep
			65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIwMAYIKwYBBQUHMAGG
			JGh0dHA6Ly9vY3NwLmNsb3VkZmxhcmUuY29tL29yaWdpbl9jYTAt
			BgNVHREEJjAkghEqLmtob2luZHZuLmV1Lm9yZ4IPa2hvaW5kdm4u
			ZXUub3JnMDgGA1UdHwQxMC8wLaAroCmGJ2h0dHA6Ly9jcmwuY2xv
			dWRmbGFyZS5jb20vb3JpZ2luX2NhLmNybDANBgkqhkiG9w0BAQsF
			AAOCAQEAB1Dx7dDJE8AjnFVGfmOpXdRqahdfILLtyaoUwN++c1i9
			qI7AJYNCq8DzaAes82g2EuYFvXL7dSv8VBsgesIzRqlE9q+G1p/2
			u1hsvaQxAspxqxOuHejATNfVYoQqMRoQOKJr43nOq+XkZUwxlqCg
			GTQSiAjkFoax64MsqrarncrI1xw8xfN6RnpMubTNrTRTdjS5M/vJ
			bIESgxUrzoLyVQsJLaVq0hhy0gZvBCEh00Ugban7bdyIN2bqSqOw
			qnkg4b5UKfu6FL8Fd/h79okU9C7Gbay599dWLpsp/c/V5NoG0GOA
			wYP2dG9yYJ5ylDsfp/iWI4wYhVEaXMxPmaLGHA==
			</data>
			<key>PayloadDisplayName</key>
			<string>Certificate</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.security.pkcs1.55262110-808f-4b83-909b-95f8eb30061a</string>
			<key>PayloadType</key>
			<string>com.apple.security.pkcs1</string>
			<key>PayloadUUID</key>
			<string>55262110-808f-4b83-909b-95f8eb30061a</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>Finally updated! Made by: Khoindvn, Tweaked by: Toasty.dev. STOP FORKING MY REPO TO REMOVE THIS, I GET NOTIFIED AND WILL CALL YOU OUT.</string>
	<key>PayloadDisplayName</key>
	<string>Khomod DNS</string>
	<key>PayloadIdentifier</key>
	<string>khoindvn.cloudflare.warp.com.profile</string>
	<key>PayloadOrganization</key>
	<string>No revokes on cash money.</string>
	<key>PayloadScope</key>
	<string>User</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>khoindvn.cloudflare-gateway.com.dnsSettings.managed</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
